### ISSUE TITLE
关于Stanford数据集

### ISSUE THREAD

**Issue by leo-frank** [hycPEXM/ares_replication#1]
Dear hyc,

十分感谢您做的工作，极大的方便了论文复现！

有个小问题要请教一下您：以论文中使用到的数据集地址为例，https://purl.stanford.edu/bn398fc4306 。 打开该页面后，没有找到下载数据的位置。

请问您是怎么解决该问题的？

**Comment by hycPEXM** [comment]
![Snipaste_2022-06-22_19-02-45](https://user-images.githubusercontent.com/55644101/175013893-ce313127-019f-4feb-863b-99757170ad27.png)
我这边有啊

**Comment by leo-frank** [comment]
感谢！
